= Contributing to Kilt

Thanks for your interest in contributing to Kilt.

== How to contribute

If you intent to do larger changes it is advisable to open an
https://github.com/poiu-de/kilt/issues[Issue] issue first, describing the
problem and the intentions. This helps avoiding duplicate work or your
changes being refused for some reason.

Of course you are free to just fork the project, do the intented changes
and create a pull request.

== What to contribute

=== Finding bugs

Every software has bugs. If you find a bug in Kilt please file an
https://github.com/poiu-de/kilt/issues[Issue] so they can be resolved.

Preparing pull requests to solve issues is also highly welcome, of course.
In that case, please provide a commit with a unit test demonstrating the
problem and another commit with the actual fix.

=== Writing code

When writing some code please follow our
https://hupfdule.github.io/styleguide/javaguide.html[code conventions].

Please structure your commits logically and respect the original
formatting.  Do not change formattings unrelated to any functional changes,
even if the existing formatting violates the styleguide.  To do such
formatting changes, please prepare a separate pull request.

=== Write unit tests

Kilt is currently only partly covered by unit tests. Writing unit tests is
good way to get familiar with the code base and at the same time providing
some value to it.

Please stick to the style of the currently existing unit tests.

It is also advisable to provide unit tests for your own code contributions.
