Kilt
====
Marco Herrn <marco@mherrn.de>
2018-05-03
:toc:
:homepage: https://github.com/hupfdule/kilt
:download-page: https://github.com/hupfdule/kilt/releases
:license-link: ./LICENSE.txt
:kilt-version: 0.3.0

[.float-group]
--
image:docs/kilt-icon.svg[Kilt - **K**een **I**18n, **L**10n and **T**9n,
role="right", width="75"]
**K**een **I**18n **L**10n and **T**9n

Create an XLS(X) sheet from Java localization resource bundles and vice versa.
--



What is Kilt
------------

Kilt is a set of small tools to convert Java i18n resource bundles to
XLS(X) and vice versa. It also contains a generator for a facade to access
the translation resources in a type-safe manner.

Kilt is available as a standalone application or as ant task
to be integrated with an ant-based application and also as a maven plugin
to be integrated with a maven-based application.

Why to use Kilt
---------------

The localizations of Java i18n resource bundles are cluttered among
serveral files. That's no problem for software engineers, but not very
helpful to translators without the help of additional professional
translation tools. Therefore this tool allows to convert the Java i18n
resource bundles to a single XLS(X) sheet to be transmitted to the
translators. The translators can make their changes directly in the XLS(X)
sheet and send it back to the software engineers who incorporate the
changes back into the actual Java i18n resource bundles.

Also using Java i18n resource bundles usually involve accessing them by
string which is not type safe and requires the knowledge of the exact name
of the key to use. Kilt can create a facade to access the resource bundle
keys in a type-safe manner. This allows for using code completion in and
IDE to find the available keys. It even lists the available translations in
the generated Javadoc!

The benefits of Kilt are in short form:

 - Support of a fast and easy translation workflow
 - Minimal invasive changes on import and export of translations (comments,
   blank lines and order remain intact)
 - Good integration into ant and maven build tools
 - Type safe access to translation resources via facade


Prerequisites
-------------

=== Basic prerequisites

 - Java 8 or higher

=== To be integrated into an ant build script

 - Apache ant 1.8.1 or higher

=== To be integrated into a maven build
 
 - Apache maven 3.0.3 or higher


Installation
------------

=== Maven plugin

To use the maven plugin of Kilt include the following plugin section in
the pom or your project:

[source,xml,subs="verbatim,attributes"]
----
  <build>  
    <plugins>
      ... 
      <plugin>
        <groupId>de.poiu.kilt</groupId>
        <artifactId>kilt-maven-plugin</artifactId>
        <version>{kilt-version}</version>
        <configuration>
          ...
        </configuration>
        <executions>
          <execution>
            <id>i18n-facade-generation</id>
            <goals>
              <goal>create-facade</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      ...
    <plugins>
  <build>  
----

See link:docs/user_guide.adoc[the Kilt User Guide] for a 
detailed description of the available goals and configuration parameters.

=== Ant task

To use the ant task of Kilt download the kilt-ant package from the
{download-page}[Download] section and either use the integrated `build.xml` file or
use it as a sample to include it in your own ant build script.

You will need the accompanied properties file and lib directory as well.

=== As standalone tool

To use Kilt as a standalone tool download the kilt-cli package from the
{download-page}[Download] section and unpack it to a directory of your choice.


Usage
-----

// Hier was schnelles hinschreiben?

See link:docs/user_guide.adoc[the main user guide] for a detailed usage
description of Kilt.


License
-------

Kilt is licensed under the terms of the link:{license-link}[Apache license 2.0].


History
-------

Kilt is based on https://github.com/alexchiri/i18n-binder[i18n-binder]
which is apparently orphaned. It started as bugfixes for i18n-binder, but
soon involved such massive changes that it was forked into a new project
with the new name *Kilt*.
