/*
 * Copyright (C) 2018 Marco Herrn
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.poiu.kilt.facade;


/**
 * Base interface for the I18n enum facades.
 * <p>
 * All enum facades generated by kilt will implement this interface.
 * This allow type safe access to the keys in these facades.
 *
 * @author mherrn
 */
public interface KiltEnumFacade {

  /**
   * Returns the bundle basename.
   * @return the bundle basename
   */
  public String getBasename();

  /**
   * Returns the localization key.
   * @return the localization key
   */
  String getKey();
}
